controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    solo12_controller:
      type: forward_command_controller/ForwardCommandController
    #  type: joint_trajectory_controller/JointTrajectoryController

solo12_controller:
  ros__parameters:
    joints:
      - FL_HAA
      - FL_HFE
      - FL_KFE
      - FR_HAA
      - FR_HFE
      - FR_KFE
      - HL_HAA
      - HL_HFE
      - HL_KFE
      - HR_HAA
      - HR_HFE
      - HR_KFE
    interface_name: position