publisher_forward_position_controller:
  ros__parameters:

    wait_sec_between_publish: 5
    publish_topic: "/forward_position_controller/commands"
    # [FL_HAA, FL_HFE, FL_KFE, 
    #  FR_HAA, FR_HFE, FR_KFE, 
    #  HL_HAA, HL_HFE, HL_KFE, 
    #  HR_HAA, HR_HFE, HR_KFE]
    #goal_names: ["pos1", "pos2", "pos3", "pos4"]
    goal_names: ["pos1"]
    pos1: [0.0, -0.378, 0.0, 0.0, -0.378, 0.0, 0.0, -0.378, 0.0, 0.0, -0.378, 0.0]
    #pos2: [0.0, -0.378, 0.0, 0.0, -0.378, 0.0, 0.0, -0.378, 0.0, 0.0, -0.378, 0.0]
    #pos3: [-0.785, -0.785]
    #pos4: [0, 0]
