controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    #feedforward_controller:
    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    solo12_controller:
      type: solo12_controller/RobotController

solo12_controller:
  ros__parameters:
    joints:
      - FL_HAA
      - FL_HFE
      - FL_KFE
      - FR_HAA
      - FR_HFE
      - FR_KFE
      - HL_HAA
      - HL_HFE
      - HL_KFE
      - HR_HAA
      - HR_HFE
      - HR_KFE
      
    command_interfaces:
      - position

    state_interfaces:
      - position
      #- velocity
      #- effort

forward_position_controller:
  ros__parameters:
    joints:
      - FL_HAA
      - FL_HFE
      - FL_KFE
      - FR_HAA
      - FR_HFE
      - FR_KFE
      - HL_HAA
      - HL_HFE
      - HL_KFE
      - HR_HAA
      - HR_HFE
      - HR_KFE
    
    interface_name: position  
    #command_interfaces:
    #  - position
    #state_interfaces:
    #  - position
      #- velocity
      #- effort